### ISSUE TITLE
CSS should not statically link MainStyles.css

### ISSUE THREAD

**Issue by caboose014** [provisioner/Provisioner#193]
I am using a custom skin with FreePBX which has an overridden mainstyle.css file. Every module is displaying as expected bar the EndPoint Manger module.

I have found that in your templates folder you are statically specifying the mainstyle.css file in the html files with the following line: `<link href="assets/css/mainstyle.css" rel="stylesheet" type="text/css" />`

This is causing my custom .css file to be overwritten with the default mainstyle.css file when browsing any page of the EndPoint Manager. There is no reason to specify this link here as this is already linked by the core FreePBX page creation, so if you look at the page source you can see that mainstyle.css is being listed twice (or in my case my custom css file, then the mainstyle.css).

These are the following files that should have this line removed (path relative to root of module):

```
templates/freepbx/advanced_settings_settings_pop.html
templates/freepbx/alt_config_popup.html
templates/freepbx/specifics_pop.html
templates/freepbx/global_header.html
```

At this point, I have just manually removed the line from these files so my css will be applied correctly to the EndPoint Manager pages. I don't want to have to redo this work each time there is an update to the mode (granted updates do not come often... but still).

Thanks,

**Comment by tm1000** [comment]
This has nothing to do with provisioner.
