### ISSUE TITLE
Can't install firmware

### ISSUE THREAD

**Issue by smccloud** [provisioner/Provisioner#206]
Whenever I try to install any firmware, I get the following error.

`Downloading firmware...Done!`
`Checking MD5sum of Package...`
`Firmware MD5 didn't match`

This makes it unusable to me, is it trying to download the firmware from a location that no longer exists?

**Comment by tm1000** [comment]
This is now fixed but was originally a FreePBX server issue and had nothing to do with Provisioner.

**Comment by smccloud** [comment]
A better error message would be nice to see :)
